CREATE TABLE product_variant(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    volume_ml VARCHAR(150) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    product_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_product_variant_category
    FOREIGN KEY (product_id) REFERENCES products(id)
);

