CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    product_id BIGINT,
    variant_id BIGINT,

    quantity INT NOT NULL,
    total_price DECIMAL(10,2),
    total_ml INT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_product
        FOREIGN KEY (product_id) REFERENCES products(id),

    CONSTRAINT fk_order_variant
        FOREIGN KEY (variant_id) REFERENCES product_variants(id)
);

