CREATE TABLE order_items(

    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,

    order_id BIGINT NOT NULL,

    product_id BIGINT NOT NULL,

    variant_id BIGINT NOT NULL,

    product_name VARCHAR(255),

    brand_name VARCHAR(255),

    volume_ml INTEGER,

    quantity INTEGER,

    unit_price NUMERIC(10,2),

    total_price NUMERIC(10,2),

    total_ml INTEGER,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_item_order
        FOREIGN KEY(order_id)
        REFERENCES orders(id),

    CONSTRAINT fk_order_item_product
        FOREIGN KEY(product_id)
        REFERENCES products(id),

    CONSTRAINT fk_order_item_variant
        FOREIGN KEY(variant_id)
        REFERENCES product_variants(id)


)