CREATE TABLE refresh_tokens (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    token TEXT NOT NULL UNIQUE,

    user_id BIGINT NOT NULL,

    expiry_date TIMESTAMP NOT NULL,

    revoked BOOLEAN DEFAULT FALSE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refresh_user
        FOREIGN KEY (user_id)
        REFERENCES users_info(id)
);